#!/usr/bin/env python3
"""
Regenerate firmware.js from a Margo DFU package (the .zip produced for the
programmer stick, containing manifest.json + *.bin + *.dat).

Usage:
    python3 make_firmware_js.py MargoProgrammerStick.zip firmware.js

The output firmware.js embeds the firmware so the web page needs no file
picker. Commit it alongside index.html to publish a new firmware version.
"""
import sys, os, json, base64, zipfile, datetime


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    zip_path, out_path = sys.argv[1], sys.argv[2]

    with zipfile.ZipFile(zip_path) as z:
        manifest = json.loads(z.read("manifest.json"))
        app = manifest["manifest"]["application"]
        bin_bytes = z.read(app["bin_file"])
        dat_bytes = z.read(app["dat_file"])

    meta = {
        "product": "Margo Programmer Stick",
        "binFile": app["bin_file"],
        "appSize": len(bin_bytes),
        "datSize": len(dat_bytes),
        "dfuVersion": manifest["manifest"].get("dfu_version"),
        "generated": datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    }

    with open(out_path, "w") as f:
        f.write("// AUTO-GENERATED by make_firmware_js.py — do not edit by hand.\n")
        f.write("// Regenerate from a new DFU .zip to publish updated firmware.\n")
        f.write("export const FW_META = " + json.dumps(meta, indent=2) + ";\n\n")
        f.write('export const FW_BIN_B64 = "' + base64.b64encode(bin_bytes).decode() + '";\n\n')
        f.write('export const FW_DAT_B64 = "' + base64.b64encode(dat_bytes).decode() + '";\n')

    print("Wrote %s  (bin %d B, dat %d B)" % (out_path, len(bin_bytes), len(dat_bytes)))


if __name__ == "__main__":
    main()
